return {
    globalSettings = {
        controlPosition = {
            x = 95,
            y = 13,
        },
        multiDragMode = false,
        hideOriginalMoodles = false,
    },
    indicators = {
        MS_ThirstIndicator = {
            position = {
                x = 298,
                y = 1377,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.55,
                g = 0.75,
                b = 0.85,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_HungerIndicator = {
            position = {
                x = 463,
                y = 1171,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.95,
                g = 0.95,
                b = 0.45,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_EnduranceIndicator = {
            position = {
                x = 362,
                y = 1365,
            },
            circularSize = 60,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.85,
                g = 0.85,
                b = 0.85,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = false,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_FatigueIndicator = {
            position = {
                x = 295,
                y = 1365,
            },
            circularSize = 60,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.7,
                g = 0.65,
                b = 0.55,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = false,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_StressIndicator = {
            position = {
                x = 245,
                y = 896,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.6,
                g = 0.6,
                b = 0.6,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_PanicIndicator = {
            position = {
                x = 245,
                y = 956,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.95,
                g = 0.65,
                b = 0.4,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_TemperatureIndicator = {
            position = {
                x = 245,
                y = 656,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 1,
                g = 0.6,
                b = 0.4,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_HealthIndicator = {
            position = {
                x = 245,
                y = 716,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 1,
                g = 0.6,
                b = 0.6,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_BoredomIndicator = {
            position = {
                x = 245,
                y = 776,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.75,
                g = 0.75,
                b = 0.75,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_UnhappynessIndicator = {
            position = {
                x = 245,
                y = 836,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.6,
                g = 0.6,
                b = 0.9,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_DiscomfortIndicator = {
            position = {
                x = 245,
                y = 896,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.65,
                g = 0.65,
                b = 0.9,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_SicknessIndicator = {
            position = {
                x = 245,
                y = 956,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.65,
                g = 0.75,
                b = 0.5,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_PainIndicator = {
            position = {
                x = 245,
                y = 716,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.95,
                g = 0.5,
                b = 0.5,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_CarryWeightIndicator = {
            position = {
                x = 245,
                y = 776,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.6,
                g = 0.4,
                b = 0.2,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_CalorieIndicator = {
            position = {
                x = 228,
                y = 1365,
            },
            circularSize = 60,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.85,
                g = 0.65,
                b = 0.4,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = false,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_ProteinsIndicator = {
            position = {
                x = 160,
                y = 1365,
            },
            circularSize = 60,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.7,
                g = 0.8,
                b = 0.4,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = false,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_CarbohydratesIndicator = {
            position = {
                x = 245,
                y = 1016,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.8,
                g = 0.6,
                b = 0.3,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_LipidsIndicator = {
            position = {
                x = 344,
                y = 1377,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.9,
                g = 0.8,
                b = 0.2,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_WeightIndicator = {
            position = {
                x = 254,
                y = 1161,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0,
                g = 1,
                b = 0,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_MedicineIndicator = {
            position = {
                x = 92,
                y = 1365,
            },
            circularSize = 60,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.3,
                g = 0.9,
                b = 0.4,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = false,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_DirtinessIndicator = {
            position = {
                x = 245,
                y = 1016,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.5,
                g = 0.4,
                b = 0.3,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_AngerIndicator = {
            position = {
                x = 273,
                y = 656,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 1,
                g = 0.1,
                b = 0.1,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_StiffnessIndicator = {
            position = {
                x = 23,
                y = 1365,
            },
            circularSize = 60,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.8,
                g = 0.6,
                b = 0,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = false,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_WetnessIndicator = {
            position = {
                x = 273,
                y = 716,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.4,
                g = 0.6,
                b = 0.9,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
        MS_DrunkennessIndicator = {
            position = {
                x = 273,
                y = 776,
            },
            circularSize = 48,
            barSize = {
                width = 168,
                height = 18,
            },
            color = {
                r = 0.8,
                g = 0.4,
                b = 0.6,
            },
            opacity = 1,
            iconOpacity = 1,
            style = "circular",
            isVertical = false,
            showIcon = true,
            useGradient = false,
            useMonoIcon = false,
            locked = true,
            hidden = true,
            animationThreshold = 20,
            alwaysShowValue = false,
            showName = true,
            textScale = 1,
            autoHide = false,
        },
    },
}